apiVersion: ouf.trieste.it/v1
kind: SourceRuntimeProfile
metadata: {id: onboarding-managed-files, version: 1.0.0, status: ACTIVE}
spec:
  protocol: FILE
  endpointRef: service://ouf-object-storage
  sourceSchemaRef: object-ref://v1

