"""Issue creation-only intent once with an existing key and explicit root mandate.

No policy/key generation, container creation, runtime registration or start.
An uncertain issuance retains its claim and cannot be retried in place.
"""
import copy
import hashlib
from pathlib import Path
import stat
import time

from tools.semantic_provider_deployment_authentication import DetachedAuthenticator, VerificationBudget, binding, private_bytes, decode, ancestors
from tools.semantic_provider_deployment_protocol import context, validate_intent, window
from tools.semantic_provider_deployment_producer import encoded
from tools.semantic_provider_deployment_signing import ExistingEd25519Signer
from tools.semantic_provider_installer_approval import require, publish_once


class CreationIntentIssuer:
    FIELDS = {'schema', 'sourceRoot', 'sourceHashes', 'pythonBinding', 'authorities',
              'creationMandateBinding', 'policyBinding', 'signatureDirectory',
              'opensslBinding', 'signingKeyBinding', 'keyRef', 'outputDirectory', 'budgetSeconds'}
    FACTS = ('containerId', 'transactionId', 'artifactHash', 'deploymentConstraintsHash',
             'transportHash', 'runtimeExecutableHash')

    def __init__(self, cfg, configuration_raw, configuration_path, clock=time.time):
        require(type(cfg) is dict and set(cfg) == self.FIELDS and cfg['schema'] == 'ouf.semantic-creation-intent-issuer.v1',
                'EXACT_CREATION_ISSUER_CONFIGURATION_REQUIRED')
        require(type(cfg['budgetSeconds']) is int and 1 <= cfg['budgetSeconds'] <= 12, 'BOUNDED_INTENT_ISSUANCE_REQUIRED')
        self.cfg, self.raw, self.path, self.clock = copy.deepcopy(cfg), configuration_raw, Path(configuration_path), clock
        self.ctx = context(cfg['authorities'])
        self.budget = VerificationBudget(cfg['budgetSeconds'])
        self.verifier = DetachedAuthenticator(cfg['policyBinding'], cfg['signatureDirectory'], cfg['opensslBinding'], clock, self.budget)
        self.inputs = {}

    def read(self, record):
        b = binding(record); path = Path(b['path']); raw = private_bytes(path)
        require(hashlib.sha256(raw).hexdigest() == b['sha256'], 'CREATION_ISSUER_INPUT_DRIFT')
        self.inputs[path] = raw
        return raw

    def stable(self, policy_raw):
        self.budget.check()
        require(private_bytes(self.path) == self.raw and self.verifier.read_policy() == policy_raw,
                'CREATION_ISSUER_CONFIGURATION_OR_POLICY_CHANGED')
        for path, raw in self.inputs.items():
            require(private_bytes(path) == raw, 'CREATION_MANDATE_CHANGED')
        for name, sha in self.cfg['sourceHashes'].items():
            require(hashlib.sha256(private_bytes(Path(self.cfg['sourceRoot']) / name)).hexdigest() == sha,
                    'CREATION_ISSUER_SOURCE_CHANGED')

    def emit(self, authorize_creation_only=False):
        require(authorize_creation_only is True, 'EXPLICIT_CREATION_ONLY_ISSUANCE_REQUIRED')
        started = self.clock()
        mandate_raw = self.read(self.cfg['creationMandateBinding']); mandate = decode(mandate_raw, 131072)
        fields = {'schema', 'issuerRef', 'installationRef', 'entityRef', *self.FACTS,
                  'issuedAt', 'expiresAt', 'issuanceAuthorized', 'infrastructureAuthorized',
                  'creationAuthorized', 'applicationStartAuthorized'}
        require(set(mandate) == fields and mandate['schema'] == 'ouf.semantic-creation-intent-mandate.v1',
                'EXACT_ROOT_CREATION_MANDATE_REQUIRED')
        require(mandate['issuanceAuthorized'] is True, 'EXPLICIT_ROOT_CREATION_MANDATE_REQUIRED')
        window(mandate, started)
        now = int(self.clock())
        intent = {k: v for k, v in mandate.items() if k != 'issuanceAuthorized'}
        intent.update(schema='ouf.semantic-deployment-intent.v1', issuedAt=now)
        raw = encoded(intent)
        # Structural validation of our exact generated bytes before any key read.
        validate_intent(raw, self.ctx, lambda payload, *args: payload == raw, self.clock)
        policy_raw = self.verifier.read_policy()
        self.stable(policy_raw)
        directory = Path(self.cfg['outputDirectory']); ancestors(directory / 'placeholder')
        s = directory.lstat()
        require(stat.S_ISDIR(s.st_mode) and s.st_uid == s.st_gid == 0 and stat.S_IMODE(s.st_mode) == 0o700,
                'PRIVATE_INTENT_OUTPUT_DIRECTORY_REQUIRED')
        signature_path = self.verifier.signature_directory / (hashlib.sha256(raw).hexdigest() + '.DEPLOYMENT_INTENT.json')
        intent_path, claim_path = directory / 'intent.json', directory / 'issuance-claim.json'
        require(not intent_path.exists() and not intent_path.is_symlink() and not signature_path.exists() and not signature_path.is_symlink(),
                'EXISTING_INTENT_EVIDENCE_PRESERVED')
        claim = encoded({'schema': 'ouf.semantic-creation-intent-issuance-claim.v1', 'state': 'ISSUING',
                         'configurationHash': hashlib.sha256(self.raw).hexdigest(),
                         'mandateHash': hashlib.sha256(mandate_raw).hexdigest(),
                         'intentHash': hashlib.sha256(raw).hexdigest(),
                         **{k: intent[k] for k in ('issuerRef', 'installationRef', 'entityRef', 'containerId', 'transactionId')}})
        publish_once(claim_path, claim, 'DO_NOT_REPLAY_CREATION_INTENT_ISSUANCE')
        signer = ExistingEd25519Signer(self.cfg['signingKeyBinding'], self.cfg['keyRef'], self.verifier,
            {'role': 'DEPLOYMENT_INTENT', **{k: intent[k] for k in ('issuerRef', 'installationRef', 'entityRef')}})
        signature = signer.sign(raw)
        authenticate = lambda payload, *args: self.verifier.verify_detached(payload, signature, *args)
        validate_intent(raw, self.ctx, authenticate, self.clock)
        self.stable(policy_raw); window(mandate, self.clock())
        require(self.clock() >= started and private_bytes(claim_path) == claim, 'CREATION_ISSUANCE_CLOCK_OR_CLAIM_CHANGED')
        # Publish the signature before its payload. Partial publication is retained.
        publish_once(signature_path, signature, 'EXISTING_INTENT_SIGNATURE_PRESERVED')
        publish_once(intent_path, raw, 'EXISTING_INTENT_PAYLOAD_PRESERVED')
        self.stable(policy_raw); window(mandate, self.clock())
        require(self.clock() >= started and private_bytes(claim_path) == claim
                and private_bytes(signature_path) == signature and private_bytes(intent_path) == raw,
                'CREATION_INTENT_PUBLICATION_CHANGED')
        validate_intent(raw, self.ctx, self.verifier, self.clock)
        return {'schema': 'ouf.semantic-creation-intent-issuance-report.v1',
                'intentHash': hashlib.sha256(raw).hexdigest(), 'signatureHash': hashlib.sha256(signature).hexdigest(),
                'mandateHash': hashlib.sha256(mandate_raw).hexdigest(), 'expiresAt': intent['expiresAt'],
                'signaturesIssued': 1, 'keysGenerated': 0, 'creationAuthorized': True,
                'applicationStartAuthorized': False, 'containerLifecycleOperations': 0,
                'runtimeRegistered': False, 'notReleaseAcceptance': True}
